# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: emerald

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'BUET'
    description: "Full-stack Software Engineer with expertise in Java, Spring Boot, AWS, and React. Passionate about building scalable applications and exploring machine learning, human-computer interaction, and bioinformatics. Committed to developing data-driven solutions and impactful technologies."
    twitter: ''
  analytics:
    google_analytics: 'G-08PK28QG2G'
    google_tag_manager: 'GTM-WNFPTFQH'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
#header:
#  navbar:
#    enable: true
#    blox: "navbar"
#    fixed_to_top: true
#    show_search: true
#    show_theme_chooser: true
#    logo:
#      text: "Raihanul Alam Hridoy"
#    align: "center"
header:
  navbar:
    # Display the navigation bar?
    enable: true
    # Choose a built-in navigation blox or create your own
    blox: "navbar"
    # Align menu links: `left`, `center`, or `right`
    align: "center"
    # Fix the navigation bar to the top of the page
    fixed_to_top: true
    logo:
      # Logo text
      text: "Raihanul Alam Hridoy"
      # Logo filename in `assets/media/` folder
#      filename: "logo.svg"
    # Shop a call-to-action button in the top right?
#    button:
#      enable: true
#      text: "Get Started"
#      url: "https://hugoblox.com/templates/"
    # Let the user choose between light or dark mode?
    show_theme_chooser: true
    # Let the user search from the navigation bar?
    show_search: true
    # Attempt to automatically highlight the active menu link? Can be disabled for complex sites.
    highlight_active_link: true
    # Show a language chooser (if you have translated your site content)?
    show_translations: true
    # If `show_translations` is enabled, do you wish to hide the current language name?
    hide_language_name: false

# Site footer
footer:
  copyright:
    notice: '© {year} Raihanul Alam Hridoy'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

  show_last_updated: true
  last_updated_text: 'Last updated on'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: true
  privacy_pack:
    enable: false

params:
  # Site last updated date - update this whenever you make changes
  last_updated: '2025-05-11'

